// <auto-generated />
using System;
using KorgiBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KorgiBot.Database.Migrations.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KorgiBot.Database.Tables.Raid", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<decimal[]>("AdminRoles")
                        .HasColumnType("numeric(20,0)[]")
                        .HasColumnName("admin_roles");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<decimal>("CreatorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FirstRequired")
                        .HasColumnType("integer")
                        .HasColumnName("first_required");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.PrimitiveCollection<decimal[]>("MessageIds")
                        .HasColumnType("numeric(20,0)[]")
                        .HasColumnName("message_ids");

                    b.Property<DateTimeOffset>("RemoveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("remove_date");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_time");

                    b.Property<decimal>("ThreadId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("pk_raids");

                    b.ToTable("raids", (string)null);
                });

            modelBuilder.Entity("KorgiBot.Database.Tables.RaidRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("MemberId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("member_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<long>("RaidId")
                        .HasColumnType("bigint")
                        .HasColumnName("raid_id");

                    b.HasKey("Id")
                        .HasName("pk_raid_roles");

                    b.HasIndex("RaidId")
                        .HasDatabaseName("ix_raid_roles_raid_id");

                    b.ToTable("raid_roles", (string)null);
                });

            modelBuilder.Entity("KorgiBot.Database.Tables.RaidRole", b =>
                {
                    b.HasOne("KorgiBot.Database.Tables.Raid", "Raid")
                        .WithMany("Roles")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_raid_roles_raids_raid_id");

                    b.Navigation("Raid");
                });

            modelBuilder.Entity("KorgiBot.Database.Tables.Raid", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
